//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// New class2.
    /// </summary>
    // *** Start programmer edit section *** (NewClass2 CustomAttributes)

    // *** End programmer edit section *** (NewClass2 CustomAttributes)
    [AutoAltered()]
    [Caption("New class2")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("NewClass2E", new string[] {
            "Номер as \'Номер\'",
            "Город as \'Город\'",
            "Город.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Город.Наименование"})]
    [MasterViewDefineAttribute("NewClass2E", "Город", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("NewClass2L", new string[] {
            "Номер as \'Номер\'",
            "Город.Наименование as \'Наименование\'"})]
    public class NewClass2 : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private int fвоЭтажей;
        
        private IIS.Test.Город fГород;
        
        // *** Start programmer edit section *** (NewClass2 CustomMembers)

        // *** End programmer edit section *** (NewClass2 CustomMembers)

        
        /// <summary>
        /// воЭтажей.
        /// </summary>
        // *** Start programmer edit section *** (NewClass2.воЭтажей CustomAttributes)

        // *** End programmer edit section *** (NewClass2.воЭтажей CustomAttributes)
        private int воЭтажей
        {
            get
            {
                // *** Start programmer edit section *** (NewClass2.воЭтажей Get start)

                // *** End programmer edit section *** (NewClass2.воЭтажей Get start)
                int result = this.fвоЭтажей;
                // *** Start programmer edit section *** (NewClass2.воЭтажей Get end)

                // *** End programmer edit section *** (NewClass2.воЭтажей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass2.воЭтажей Set start)

                // *** End programmer edit section *** (NewClass2.воЭтажей Set start)
                this.fвоЭтажей = value;
                // *** Start programmer edit section *** (NewClass2.воЭтажей Set end)

                // *** End programmer edit section *** (NewClass2.воЭтажей Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (NewClass2.Номер CustomAttributes)

        // *** End programmer edit section *** (NewClass2.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (NewClass2.Номер Get start)

                // *** End programmer edit section *** (NewClass2.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (NewClass2.Номер Get end)

                // *** End programmer edit section *** (NewClass2.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass2.Номер Set start)

                // *** End programmer edit section *** (NewClass2.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (NewClass2.Номер Set end)

                // *** End programmer edit section *** (NewClass2.Номер Set end)
            }
        }
        
        /// <summary>
        /// New class2.
        /// </summary>
        // *** Start programmer edit section *** (NewClass2.Город CustomAttributes)

        // *** End programmer edit section *** (NewClass2.Город CustomAttributes)
        [PropertyStorage(new string[] {
                "Город"})]
        [NotNull()]
        public virtual IIS.Test.Город Город
        {
            get
            {
                // *** Start programmer edit section *** (NewClass2.Город Get start)

                // *** End programmer edit section *** (NewClass2.Город Get start)
                IIS.Test.Город result = this.fГород;
                // *** Start programmer edit section *** (NewClass2.Город Get end)

                // *** End programmer edit section *** (NewClass2.Город Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass2.Город Set start)

                // *** End programmer edit section *** (NewClass2.Город Set start)
                this.fГород = value;
                // *** Start programmer edit section *** (NewClass2.Город Set end)

                // *** End programmer edit section *** (NewClass2.Город Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "NewClass2E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass2E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass2E", typeof(IIS.Test.NewClass2));
                }
            }
            
            /// <summary>
            /// "NewClass2L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass2L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass2L", typeof(IIS.Test.NewClass2));
                }
            }
        }
    }
}
